# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'API Document' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for API Document
  pod 'Alamofire', '~> 5.1'

  target 'API DocumentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'API DocumentUITests' do
    # Pods for testing
  end

end
